FROM swaggerapi/swagger-ui

# Expose the standard Swagger UI port
EXPOSE 8080

# Set the default API URL to point to the PostgREST service
# This assumes the PostgREST service is accessible at localhost:3000 from the browser
ENV API_URL="http://localhost:3000/"
